version: '3'

services:
  mongodb:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_db:/data/db

  app:
    build: .
    ports: 
     - 4000:3000
    environment:
      MONGO_URI: "mongodb+srv://user:pass@cluster0.example.mongodb.net/ChatApplication"
      PORT: 3000
      JWT_SECRET_KEY: secretkey123
    depends_on:
      - mongodb

volumes:
  mongodb_db: {}